<?php

$encoded = 'PD9waHAgZWNobyAnbWFsaWNpb3VzJzsgPz4=';
$runner = 'assert';
@$runner(base64_decode($encoded));

$payload = 'QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB';
$x = chr(101).chr(118).chr(97).chr(108).chr(40).chr(41).chr(59);

eval(
    base64_decode($payload)
);

